### PR TITLE
Update context.py

### LINKED ISSUE #167: Portals not working
In Legacy mode result is clear distinct
In Full black screen

### PR DESCRIPTION
**Pull request by bsavery**
### PURPOSE
Portal lights are not supported or needed in rpr2 

### EFFECT OF CHANGE
Hide portal light checkbox and skip functionality if not Legacy mode.  Closes #167

### CODE REVIEW

**Review by bnagirniak — COMMENTED** [review]
Can't find in code changes part of hiding portal lights checkbox for non-legacy mode, as it is written in Effect of Change. Maybe something wasn't committed?

**Comment by ardraeiss** [comment]
Added UI disabling code for non-Legacy modes.

**Review by ardraeiss — APPROVED** [review]
Portal skipping part works correctly.

**Review by bnagirniak — APPROVED** [review]

**Comment by bsavery** [comment]
Thanks Mikhail.  Missd a checkin file.

**Pull request merged**
