### PR TITLE
RPRBLND-2174: HybridPro review/add light support

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
HybridPro review/add light support.

### EFFECT OF CHANGE
Added support for IESLight in Point Light.

### TECHNICAL STEPS
Implemented IESLight.

### NOTES FOR REVIEWERS
Should work SDK 2.2.16 and higher.

Point Light intensity HybridPro is higher than in NorthStar. [ticket](https://amdrender.atlassian.net/browse/RPRHYB-651)
Spot Blend setting for Spot Light is unsupported in HybridPro. [ticket](https://amdrender.atlassian.net/browse/RPRHYB-650)
Spot Ligh DiskLightSetAngle produces twice smaller angle compare to NorthStar (it can be fixed in addon). [ticket](https://amdrender.atlassian.net/browse/RPRHYB-649).
DiskLight, SphereLight. need more work to be done.

### CODE REVIEW

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Comment by VascoPi** [comment]
Found mesh intersection issue for HybridPro renderer SphereLight, created [ticket](https://amdrender.atlassian.net/browse/RPRHYB-732)
image

compare to NorthStar renderer
image

**Review by bnagirniak — APPROVED** [review]
Looks good

**Comment by bsavery** [comment]
> Found mesh intersection issue for HybridPro renderer SphereLight, created [ticket](https://amdrender.atlassian.net/browse/RPRHYB-732) image
> 
> compare to NorthStar renderer image

Probably not a blocker IMO

**Comment by VascoPi** [comment]
Added only IES light support.

**Review by ARozghon — APPROVED** [review]
Approved by QA with the final iteration

**Pull request merged**
