### PR TITLE
Fix build on latest macos

### PR DESCRIPTION
**Pull request by bsavery**
### PURPOSE
Fixes build errors on modern macOS.  References in #154 

### EFFECT OF CHANGE
macOS builds in big sur (and catalina?)

### TECHNICAL STEPS
Note.  The change to remove symbols starting with __ in the castxml xml is a HACK.  What is happening is castxml puts every system define in the xml including stuff like 
`<Typedef id="_97" name="__darwin_pthread_t" type="_295" context="_1" location="f14:118" file="f14" line="118"/>`
which is where the error was happening.  My solution gets around that. 

Also note there were OpenMP symbols missing when helper lib compiled

@BumpierZulu9930 please try.

### CODE REVIEW

**Comment by BumpierZulu9930** [comment]
It's been built successfully! This is the terminal output (if wanted):
[Terminal_Output.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5693825/Terminal_Output.txt)

**Comment by bnagirniak** [comment]
Seems there are problems with plugin initialization on MacOS on CIS machines: https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3208/Test_20Report/
All MacOS tests failed.

**Review by bnagirniak — CHANGES_REQUESTED** [review]
Tested this PR on CIS, plugin doesn't start on MacOS https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3208/Test_20Report/

**Comment by bsavery** [comment]
This is needed for others.
If CIS builds fail install openmp

**Pull request merged**
