### PR TITLE
RPRBLND-2266: Add support for FloatCurve node

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Add support for FloatCurve node.

### EFFECT OF CHANGE
Added support for FLoat Curve node.

### TECHNICAL STEPS
Implemented ShaderNodeFloatCurve.
Improved code for ShaderNodeRGBCurve.

### CODE REVIEW

**Comment by ARozghon** [comment]
manually working as expected

**Review by DagerD — CHANGES_REQUESTED** [review]
discussed offline

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Review by bnagirniak — APPROVED** [review]
Looks good

**Pull request merged**
