### PR TITLE
Core 2.2.15

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Update RadeonProRenderSDK to core_2.2.15.

### EFFECT OF CHANGE
Updated RadeonProRenderSDK to core_2.2.15.
Added Pixel Filter panel. Render Properties -> Quality -> Pixel Filter.

### TECHNICAL STEPS
Enabled Pixel Filter panel for "Final" render quality.
Fixed build process, excluded 'rprContextCreateMeshInstanceWithUniqueAttributes'.
Fixed SDK API changes:
* Those context parameter have been removed :
      RPR_CONTEXT_IMAGE_FILTER_BOX_RADIUS
      RPR_CONTEXT_IMAGE_FILTER_GAUSSIAN_RADIUS
      RPR_CONTEXT_IMAGE_FILTER_TRIANGLE_RADIUS
      RPR_CONTEXT_IMAGE_FILTER_MITCHELL_RADIUS
      RPR_CONTEXT_IMAGE_FILTER_LANCZOS_RADIUS
      RPR_CONTEXT_IMAGE_FILTER_BLACKMANHARRIS_RADIUS
    and replaced by a single parameter : RPR_CONTEXT_IMAGE_FILTER_RADIUS.

* typo fixed:  RPR_CONTEXT_RAY_CAST_EPISLON  -->  RPR_CONTEXT_RAY_CAST_EPSILON

### CODE REVIEW

**Comment by ARozghon** [comment]
image
in Blender Cycles, Pixel filters are located in the "Film" menu, so, for blender it we be better to add in the same menu for RPR plugin too

**Review by ARozghon — APPROVED** [review]
core approved by QA

**Review by DagerD — APPROVED** [review]

**Review by bsavery — CHANGES_REQUESTED** [review]
The pixel filter type should be removed right?

**Comment by ARozghon** [comment]
pixel filters are now supported and added to the Quality menu, why do we need to remove them? In the Film menu, we have an option only for transparent BG, as discussed earlier

**Comment by bsavery** [comment]
The TYPE of pixel filter is no longer supported in Northstar right?  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/blob/484351d95d5d20559331171c58bbb98fea516a66/release_notes.txt#L27

I'm not saying we remove the filter setting, just the type

**Comment by VascoPi** [comment]
I see it written about TYPE of pixel filter RADIUS, so RPR_CONTEXT_IMAGE_FILTER_RADIUS is a general parameter for all pixel filters, and we don't need to generate it depending on a particular filter type anymore.

**Review by bnagirniak — APPROVED** [review]
Looks good, QA tested and approved.

**Review by bsavery — CHANGES_REQUESTED** [review]
Please remove   col.prop(rpr_scene, 'pixel_filter') from UI since it is not used.

**Pull request merged**
