### PR TITLE
Fix: ShaderNodeMapping Rotation Input Value (Fixes #606)

### LINKED ISSUE #606: Vector->Mapping node Rotation input doesnt work
1.  System setup (GPU, CPU, OS version, Blender version)
       Win11, Vega64, xeon e5 2696v4, blender 3.5.0

Blend file attached:
[shadertestsproender.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11227099/shadertestsproender.zip)

Setup:

Texture UV coordinate runs into Vector->Mapping node to rotate the texture on the surface.

Typing a value into the Z rotation box works fine.

Connecting a vector input to the "Rotation" input doesnt change anything, and the mapping node proceeds to use the same value that was typed in the box instead of using the input.

The rest of the inputs on the Vector->Mapping node work as expected.

Screenshots (bad nodes highlighted in red)

Default values:
image

Scale input attached:
image

Z rotation input entered manually:
image

Rotation input node attached:
image

Rotation input node attached and value changed:
image

Please notice how the Rotation input is still using the value of 45 degrees that I had previously entered, and is not reset to 0, or even 20 from the input node.

Sorry for any formatting errors, and please let me know if I missed something, or you have any questions.

### PR DESCRIPTION
**Pull request by jombo23**
### PURPOSE
Fixes the Vector Mapping Rotation input node not working.

### EFFECT OF CHANGE
The Vector Mapping Rotation input node will now work as expected

### TECHNICAL STEPS
Changed "get_input_default" to "get_input_value" which polls the value on the input of the node instead of the default value in the node

### NOTES FOR REVIEWERS
Tested Locally on a single project. Everything works as expected

### CODE REVIEW

**Comment by jombo23** [comment]
Depending on the source, there are occasionally 3 and 4 element vectors intermixed for the rotation Input.  Please check and change my method of handling this (slicing) if needed, as python is not my forte.

**Comment by jombo23** [comment]
It has come to my attention that the rotation does not work if the input type relies on data from the object, such as random, etc, As it is referred to as a "MaterialNode", however it works with a handful of other sources and modifiers.

At this point I believe it is over my head, and needs to be corrected by someone else.

The core issue has at least been pointed out.

**Comment by bsavery** [comment]
Sorry, just to be clear, can you attach a scene where it is not working?

**Comment by jombo23** [comment]
In which instance are you referring to it not working? 

#606 contains a scene where it doesnt work in the released RPR plugin. Are you asking for a scene in which my changes no longer work properly?

**Comment by bsavery** [comment]
Yes, a scene for what you describe above that this change doesn't work.  We can take it from there.

**Comment by jombo23** [comment]
Absolutely, here you go!

The error is achieved through attaching the "Object Info->Random" output in any way/shape/form to the "Vector->Mapping->Rotation" input 

[shadertestsproender.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11237468/shadertestsproender.zip)

Troublesome node..

image

**Comment by bsavery** [comment]
@VascoPi can you take a look?

**Comment by odil24** [comment]
> Absolutely, here you go!
> 
> The error is achieved through attaching the "Object Info->Random" output in any way/shape/form to the "Vector->Mapping->Rotation" input
> 
> [shadertestsproender.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11237468/shadertestsproender.zip)
> 
> Troublesome node..
> 
> image

Can you paste console error for this node? It looks like this node has been changed (e.g.: added new options into the node) and you have tried to open previous blend file which has been this node when worked.

**Comment by jombo23** [comment]
Replying from my phone.

Sure, I can paste the error later. please realize I colored the node red for the sake of being able to see it. it's not red because it's invalid. (I'm assuming you glanced at it and it just looks like it's an invalid node)

**Comment by jombo23** [comment]
Adding the "Object Info->Randomness" output into the input of the "Vector->Mapping->Rotation" input in any way causes it to say:
"    sin_x, sin_y, sin_z = map(math.sin, rotation.data[0:3])
TypeError: 'MaterialNode' object is not subscriptable"

And if you remove my slicing (to chop the four element vectors down)

"    sin_x, sin_y, sin_z = map(math.sin, rotation.data)
TypeError: 'MaterialNode' object is not iterable"


Both referencing line ~2050 in blender_nodes.py (file referenced in PR)


Before the PR, the code calls get_input_default, which seems to ignore any nodes connected, and only accepts constants to be entered in on the node itself.

**Review by bnagirniak — APPROVED** [review]
Looks good

**Comment by VascoPi** [comment]
At the moment Rotation input ignors all links, only default input affect mapping.

image

Regarding errors that occurs in suggested solution it's because Random output (as well as many others) is MaterialNode type witch requires a bit different support than built-in python types. Basicaly the solution is correct but requires more work to handle MaterialNode.

I've made some changes to support MaterialNode.
Let me know whether it is a desirable result:

image

**Comment by jombo23** [comment]
I'm very curious as to what changes were required for pulling the correct information from the different type, but i can't seem to locate if/where you posted them. I checked your prorender branches, etc. I write embedded c, so I'm unfamiliar with the SOP of python, but I'd still like to have a look for the sake of me possibly being able to fix other bugs in the future.

**Comment by VascoPi** [comment]
I'm currently working on providing the solution and should be able to deliver it shortly.

**Comment by VascoPi** [comment]
https://github.com/VascoPi/RadeonProRenderBlenderAddon/tree/issue_606

Here's the branch. It requires review.

**Comment by jombo23** [comment]
Aha! I was close in my own testing, as get_channel seemed like a candidate, but I didn't know that you could call the trig operators directly on the input itself.

Thanks a bunch! I will evaluate this in my own use cases and will post if I stumble across any other edge cases.

**Comment by VascoPi** [comment]
May I ask you to update the pull request with the provided changes, so others cam review it?

**Comment by jombo23** [comment]
Absolutely!

I am on my phone currently but I will be at my workstation within the hour :)

**Comment by jombo23** [comment]
PR Updated.

In my own testing scenarios everything works as expected!

**Review by bsavery — APPROVED** [review]

**Review by VascoPi — APPROVED** [review]

**Review by DagerD — APPROVED** [review]

**Comment by jombo23** [comment]
@VascoPi  Done

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Pull request merged**
