### PR TITLE
Add Shadow Color property

### PR DESCRIPTION
**Pull request by bsavery**
### PURPOSE
Add support for Colored shadows for 2.2.9

### EFFECT OF CHANGE
User can override shadow color for objects

### CODE REVIEW

**Comment by ARozghon** [comment]
waiting for PR-414 merge to start to check this PR, because this feature is available with core 2.2.9 and later

**Comment by bsavery** [comment]
> waiting for PR-414 merge to start to check this PR, because this feature is available with core 2.2.9 and later

Merged

**Comment by ARozghon** [comment]
working with core 2.2.10

**Review by VascoPi — APPROVED** [review]
Looks good, tested

**Pull request merged**
