### PR TITLE
RPRBLND-2221: RAM leak with multiple material set with Displacement only (ALTERNATIVE)

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
RAM leak with multiple material set with Displacement only.

### EFFECT OF CHANGE
Fixed Blender memory leak in certain cases.

### TECHNICAL STEPS
Commented unused code.
Added comments.

### NOTES FOR REVIEWERS
This changes should be verified after this https://amdrender.atlassian.net/browse/RPR-1149
PR to apply after adaptive_subdivision improvements from core side https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/557

### CODE REVIEW

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Review by bnagirniak — APPROVED** [review]
Seems setting subdivision level to 10 takes too much memory and cpu. Ok with such changes.

**Comment by bsavery** [comment]
I thought the whole point of the subdivision cap was it would limit things.  Guess that doesn't work as we expected.

**Comment by mudapanda2** [comment]
Is this what's been nuking my machine in #564 ?

**Comment by bsavery** [comment]
@mudapanda2 what version RPR plugin do you have there?  This should be fixed in 3.5

**Comment by mudapanda2** [comment]
@bsavery  3.5 

Did a new rprtrace at debug level and the new play1 got to this in a render of default cube after using displacement fuzzy carpet material 

//rprFrameBufferGetInfo(framebuffer_0x000001732F1C67A0,RPR_FRAMEBUFFER_DATA,(size_t)5519280,);  RPRTRACE_CHECK
status = rprContextResolveFrameBuffer(context_0x000001732F1C7C40,framebuffer_0x000001732F1C6200,framebuffer_0x000001732F1C67A0,true);  RPRTRACE_CHECK
status = rprContextSetParameterByKey1u(context_0x000001732F1C7C40,RPR_CONTEXT_FRAMECOUNT,(rpr_uint)98);  RPRTRACE_CHECK
status = rprContextSetParameterByKey1u(context_0x000001732F1C7C40,RPR_CONTEXT_ITERATIONS,(rpr_uint)30);  RPRTRACE_CHECK
status = rprContextRender(context_0x000001732F1C7C40);  RPRTRACE_CHECK
//rprFrameBufferSaveToFile(framebuffer_0x000001732F1C6200, **"img_00765.png")**; // <-- uncomment if you want export image

In the viewport, the .bin rprtrace data .bin is 2gb,

**Pull request merged**
