### PR TITLE
Rpr sdk 2.2.2

### PR DESCRIPTION
**Pull request by bsavery**
### PURPOSE
Move to RPR SDK 2.2.2.  Numerous fixes:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/blob/5744eb4eeac42d92e60f1913ca3c3aa828d287d0/release_notes.txt#L6

### EFFECT OF CHANGE

- Adds SSS and volume shader support (CPU Only for now) #239  #71 #164 
- Fix white edge on Uber shader #67 
- Fix Adaptive sampling on CPU #252

### CODE REVIEW

**Comment by bsavery** [comment]
TODO for developers:

- Switch to use per face material setting instead of splitting meshes? 
- Investigate Procedural Textures
- Make new Toon shading workflow (using contour render and a pass with toon shader)

**Comment by bsavery** [comment]
QA status?

**Comment by bnagirniak** [comment]
QA found issues in Core, they are going to discuss them in chats.

**Review by bnagirniak — APPROVED** [review]

**Review by Dizzyspb — APPROVED** [review]
Core 2.2.3 integration is tested by QA. Approved for merge.

**Pull request merged**
