### PR TITLE
RPRBLND-2130: Error with "Material Preview" Viewport Shading mode

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Error with "Material Preview" Viewport Shading mode.
Ignoring changes in Viewport Shading panel while viewport render.

### EFFECT OF CHANGE
Fixed error while using "Material Preview" Viewport Shading mode.
Fixed ignoring changes in Viewport Shading panel while viewport render.

### TECHNICAL STEPS
Added init_from_world and init_from_shading_data for AtmosphereData.
Improved WorldData init_from_shading_data method adding FogData.init_from_shading_data AtmosphereData.init_from_shading_data.
Improved sync_update method so Viewport Shading changes now affect a result.
Added comments.

### CODE REVIEW

**Comment by ARozghon** [comment]
working correctly with Blender 3.1.2

**Comment by ARozghon** [comment]
one update: Material preview Viewport Shading settings changes not updated in real time

**Comment by ARozghon** [comment]
working correctly with the latest update.

**Review by bnagirniak — APPROVED** [review]
Tested - works good.

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Pull request merged**
