### PR TITLE
RPRBLND-2097:The camera move response is bad if you set "Camera to View"

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
The camera move response is bad if you set "Camera to View"

### EFFECT OF CHANGE
Smooth camera move response while Viewport render.

### TECHNICAL STEPS
Added condition for camera object in sync_update method.

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Looks good

**Review by DagerD — CHANGES_REQUESTED** [review]
got with standard scene:

```
2022-02-16 17:41:44,319 ERROR rpr.init [25616]:  'Object' object has no attribute 'is_updated_geometry' EXCEPTION: Traceback (most recent call last):
  File "C:\GPUOpen\RadeonProRenderBlenderAddon\src\rprblender\__init__.py", line 160, in view_update
    self.engine.sync_update(context, depsgraph)
  File "C:\GPUOpen\RadeonProRenderBlenderAddon\src\rprblender\engine\viewport_engine.py", line 562, in sync_update
    and not all(updates[0][0].is_updated_geometry, updates[0][0].is_updated_transform):
AttributeError: 'Object' object has no attribute 'is_updated_geometry'
```

**Comment by VascoPi** [comment]
> got with standard scene (blender 2.93.0):
> 
> ```
> 2022-02-16 17:41:44,319 ERROR rpr.init [25616]:  'Object' object has no attribute 'is_updated_geometry' EXCEPTION: Traceback (most recent call last):
>   File "C:\GPUOpen\RadeonProRenderBlenderAddon\src\rprblender\__init__.py", line 160, in view_update
>     self.engine.sync_update(context, depsgraph)
>   File "C:\GPUOpen\RadeonProRenderBlenderAddon\src\rprblender\engine\viewport_engine.py", line 562, in sync_update
>     and not all(updates[0][0].is_updated_geometry, updates[0][0].is_updated_transform):
> AttributeError: 'Object' object has no attribute 'is_updated_geometry'
> ```

fixed

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Pull request merged**
