### PR TITLE
RPRBLND-1896: Case scene.world == None isn't handled by plugin.

### PR DESCRIPTION
**Pull request by DagerD**
PURPOSE
There is errors in console during rendering and UI operations if we delete world light from scene.

EFFECT OF CHANGE
No more errors if world light doesn't exist.

TECHNICAL STEPS
Added checks for world light everywhere it is needed

### CODE REVIEW

**Review by VascoPi — CHANGES_REQUESTED** [review]
Still got the issue in Legacy, High, Mid, Low modes, while Viewport render.

**Review by bnagirniak — CHANGES_REQUESTED** [review]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\amd-gpuopen\RadeonProRenderBlenderAddon\cmd_tools/test_rpr.py", line 32, in <module>
    import rprblender
  File "D:\amd-gpuopen\RadeonProRenderBlenderAddon\src\rprblender\__init__.py", line 50, in <module>
    from .engine.preview_engine import PreviewEngine
  File "D:\amd-gpuopen\RadeonProRenderBlenderAddon\src\rprblender\engine\preview_engine.py", line 118
    self.rpr_context.enable_aov(pyrpr.AOV_COLOR)
    ^
IndentationError: expected an indented block
```

**Review by bnagirniak — APPROVED** [review]
Tested - works good

**Review by VascoPi — APPROVED** [review]
Looks good, and World Properties panel behavior is correct.

**Pull request merged**
