### PR TITLE
Render settings presets and simplification

### PR DESCRIPTION
**Pull request by bsavery**
### PURPOSE
The goal here is to simplify settings and give easy presets for users.  There will now be:

1.  Separate Quality settings
2.  Separate Final and viewport render mode (default Full mode for final, Interactive mode for viewport (viewport on mac needs to use Full I suppose)
3.  Quality presets which will set sampling levels, upscaling, etc.

@VascoPi  There are some TODOS here:
1.  Implement final and viewport render modes on back end. 
2.  Implement the Quality preset setting functions
3.  Remove upscaling and denoising if not using Interactive mode
4.  Make the "Denoise" button use the built in Blender Denoiser (OpenImageDenoise)

image

### EFFECT OF CHANGE
Add quality section of settings which easily allows switching mode and quality presets

### TECHNICAL STEPS
Changes made to code.

### NOTES FOR REVIEWERS
Notes, if needed.

### CODE REVIEW

**Comment by bsavery** [comment]
@VascoPi the presets should set the:
1.  sampling levels
2.  ray depth
3. denoise / upscale quality

**Comment by ARozghon** [comment]
today discussed about render settings

**Review by bnagirniak — COMMENTED** [review]
Changes looks good. 
Bug in device changes, discussed online.

**Comment by VascoPi** [comment]
> Changes looks good. Bug in device changes, discussed online.

fixed https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/584/commits/f1101a30a46c7be1c075333c03567e29cb3325f0

**Review by bnagirniak — APPROVED** [review]
Looks good, need QA to approve

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Pull request merged**
