### PR TITLE
RPRBLND-2140: add RPR_CONTEXT_RANDOM_SEED we can set the random seed of the renderer

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
add RPR_CONTEXT_RANDOM_SEED we can set the random seed of the renderer.

### EFFECT OF CHANGE
Added Seed and feature that allows managing seed value of render noise pattern (same as Cycles).

### TECHNICAL STEPS
Added seed int property.
Added anim_seed bool property.
Added set_random_seed that setting RPR_CONTEXT_RANDOM_SEED parameter.
Added UI element 'Seed' and 'Anim Seed'.

### NOTES FOR REVIEWERS
Implemented for Final render.
Discussed with HybridPro team some differences in behavior Final/Interactive and RPR_CONTEXT_RANDOM_SEED parameter. Probably the feature will be implemented in the future.

### CODE REVIEW

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Comment by bsavery** [comment]
My only comment is this should be an "advanced" option

**Review by ARozghon — APPROVED** [review]
seeds and random seeds working fine

**Comment by VascoPi** [comment]
> My only comment is this should be an "advanced" option

Moved 'Seed' to 'Advanced' panel.
image

**Review by bnagirniak — APPROVED** [review]
Looks good.

**Pull request merged**
