### PR TITLE
Enabled texture compression for Full render quality mode

### PR DESCRIPTION
**Pull request by ardraeiss**
### PURPOSE
Display and use texture compression option for Full render quality mode.

### EFFECT OF CHANGE
- added "Use texture compression" option to the Render Quality settings tab in Full mode.

### TECHNICAL STEPS
- added texture compression option;
- set texture compression by user settings in FULL2 render quality mode.

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Code is ok.

**Comment by bsavery** [comment]
My question is if we want to move this to somewhere more hidden.  Ie. most users should not use this.  We could put it by the texture cache setting.

**Comment by ardraeiss** [comment]
The SDK fix is required for this feature to have effect on render results. Closing this PR until that moment.

**Comment by ardraeiss** [comment]
> 
> 
> My question is if we want to move this to somewhere more hidden. Ie. most users should not use this. We could put it by the texture cache setting.

Sure, I'll move it to the Debug panel.

**Pull request closed without merging**
