### PR TITLE
RPR 3.1.0 vs Cycles Principled Hair Color Rendering Discrepancies (#238)

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Github issue https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/238.
Make a more expectable/predictable result of ShaderNodeBsdfHairPrincipled in with melanin mode.

### EFFECT OF CHANGE
The result of a melanin slider is more expectable /predictable.

### TECHNICAL STEPS
Changed now MATERIAL_INPUT_UBER_BACKSCATTER_WEIGHT takes into account melanin ratio.
Code cleanup.

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Looks good

**Review by bsavery — APPROVED** [review]

**Comment by VascoPi** [comment]
> Got this if not Melanin Concentration selected.
> 
> ```
> 2021-09-09 23:59:06,782 ERROR rpr.viewport_engine [27224]:  local variable 'melanin' referenced before assignment EXCEPTION: Traceback (most recent call last):
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\engine\viewport_engine.py", line 458, in _do_sync_render
>     self._do_sync(depsgraph)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\engine\viewport_engine.py", line 261, in _do_sync
>     object.sync(self.rpr_context, obj,
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\export\object.py", line 68, in sync
>     hair.sync(rpr_context, obj)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\export\hair.py", line 152, in sync
>     rpr_material = particle.get_particle_system_material(rpr_context, p_sys, emitter)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\export\particle.py", line 44, in get_particle_system_material
>     return material.sync(rpr_context, slot.material, obj=emitter)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\export\material.py", line 90, in sync
>     rpr_material = node_parser.final_export(input_socket_key)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\blender_nodes.py", line 106, in final_export
>     return self.export(input_socket_key)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\blender_nodes.py", line 70, in export
>     rpr_node = self.get_input_link(input_socket_key)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\node_parser.py", line 154, in get_input_link
>     result = self._export_node(link.from_node, link.from_socket)
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\node_parser.py", line 103, in _export_node
>     return node_parser.final_export()
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\node_parser.py", line 296, in final_export
>     node_item = self.export_rpr2()
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\node_parser.py", line 316, in export_rpr2
>     return self.export()
>   File "C:\AMD\RadeonProRenderBlenderAddon\src\rprblender\nodes\blender_nodes.py", line 1067, in export
>     node = self._create_absorption_node(color, melanin, roughness, roughness_radial, coat, ior)
> UnboundLocalError: local variable 'melanin' referenced before assignment
> ```
Fixed

**Comment by VascoPi** [comment]
Need more work, in some cases still an incorrect result. Working on that.

**Comment by VascoPi** [comment]
Moved to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/358

**Pull request closed without merging**
