### PR TITLE
RPRBLND-2074: Adjust code to Blender 3.0+

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Adjust code to Blender 3.0+ and fix error messages in console.

### EFFECT OF CHANGE
Improve compatibility with blender 3.0 +.
Fixed inputs and output colors of RPR Math node.
Moved Emissive Intensity to inputs in RPR Uber node.

### TECHNICAL STEPS
Added key 'doc_url' for bl_info (also leave 'wiki_url' for 2.8), didn't use "if statement" because of Blender restrictions.
Removed faulthandler to prevent error messages in console.

Added/Registered Interface classes for every Socket class:
RPRSocketColorInterface,
RPRSocketFloatInterface,
RPRSocketWeightInterface,
RPRSocketWeightSoftInterface,
RPRSocketMin1Max1Interface,
RPRSocketLinkInterface,
RPRSocketIORInterface,
RPRSocket_Float_Min0_SoftMax10Interface,
RPRSocketAngle360Interface,
RPRSocketValueInterface.

Fixed socket color values.
Fixed input/output socket color for class RPRValueNode_Math,
Moved Emission Intensity to inputs in class RPRShaderNodeUber

### CODE REVIEW

**Review by bnagirniak — APPROVED** [review]
Looks good

**Review by DagerD — APPROVED** [review]

**Comment by VascoPi** [comment]
Moved fixes with node sockets to this PR because the bug appears from blender 3.0 and upper.

**Review by bnagirniak — APPROVED** [review]
Tested - works correct

**Review by DagerD — APPROVED** [review]

**Comment by VascoPi** [comment]
Moved to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/454

**Comment by VascoPi** [comment]
Moved to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/454

**Pull request closed without merging**
