### PR TITLE
RPRBLND-1864: Add support for "Volume Info" node

### PR DESCRIPTION
**Pull request by bnagirniak**
### PURPOSE
RPR 2.2.6 has a node for connecting to a volume grid.  This can be used to support the Blender "Volume Info" node.

### EFFECT OF CHANGE
Implemented support of Volume Info node. Activated grid attributes in Principled Volume node.

### TECHNICAL STEPS
1. Implemented ShaderNodeVolumeInfo with export_rpr2() method which provides required grid data node.
2. Implemented get_grid_data() in ShaderNodeVolumePrincipled.export_rpr2() which provides required grid data depending of grid attribute. Made some fixes in ShaderNodeVolumePrincipled.
3. Implemented utils.get_domain_resolution() adjusted code.

### CODE REVIEW

**Review by VascoPi — APPROVED** [review]
Tested. Looks good!

**Comment by ARozghon** [comment]
PR -tested, no crashes, and volume info node shows result

**Review by ARozghon — APPROVED** [review]
Manual and CIS test complete correct

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Pull request merged**
