### PR TITLE
Update outdated, build fix for 4.1

### PR DESCRIPTION
**Pull request by takahiroharada**
### PURPOSE
- Updated readme. 
- Removed unused files. 
- Fix TC build
- Fix macos arm build. 

Builds with [aa21e5d](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/682/commits/aa21e5d35e9abd446291f1c7dc2e8247723a7ed8). 
https://www.dropbox.com/scl/fo/qtgxq8abfskfqfyt65ngp/ANLN-Ss0ak2QbaLWQpQFRuM?rlkey=iiil92eh6ycgz7o2xzb2z8fhz&st=np80hmsu&dl=0

### CODE REVIEW

**Comment by takahiroharada** [comment]
The build is [here](http://arrtc.amd.com:8111/viewLog.html?buildId=113727&buildTypeId=RadeonProRender_Plugins_RadeonProRenderBlenderAddon)

**Comment by shoikeda** [comment]
When I tried the blender plug-in with blender 4.1.1, it looks lights disappeared on interactive rendering and final render crashed.
blender

**Review by feniksa — APPROVED** [review]
Looks good for me

**Comment by odil24** [comment]
@takahiroharada @shoikeda @feniksa 
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/683

**Comment by takahiroharada** [comment]
Yes, we'll check the issue in another branch.

**Comment by odil24** [comment]
> Yes, we'll check the issue in another branch.

Ok, will wait asap

**Pull request merged**
