### PR TITLE
RPRBLND-2088: Support RPR in Blender 3.1

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Support RPR in Blender 3.1
Fixed inputs and output colors of RPR Math node.
Moved Emissive Intensity to inputs in RPR Uber node.

### EFFECT OF CHANGE
Support RPR in Blender 3.1. Moved Emissive Intensity to inputs in RPR Uber node.

### TECHNICAL STEPS
Added python 3.10 to a build scripts.
Added key 'doc_url' for bl_info (also leave 'wiki_url' for 2.8), didn't use "if statement" because of Blender restrictions.
Removed faulthandler to prevent error messages in console.
Added self.socket_value_update(context) in rpr_nodes.

Added/Registered Interface classes for every Socket class:

- RPRSocketColorInterface,
- RPRSocketFloatInterface,
- RPRSocketWeightInterface,
- RPRSocketWeightSoftInterface,
- RPRSocketMin1Max1Interface,
- RPRSocketLinkInterface,
- RPRSocketIORInterface,
- RPRSocket_Float_Min0_SoftMax10Interface,
- RPRSocketAngle360Interface,
- RPRSocketValueInterface.

Fixed socket color values.
Fixed input/output socket color for class RPRValueNode_Math,
Moved Emission Intensity to inputs in class RPRShaderNodeUber
Fixed gamma issue and ocio warning using Blender 3.0 config.osio instead of Blender 3.1
Added ability to add custom config.ocio for specific Blender version.
Small fixes.

### NOTES FOR REVIEWERS
Need to be tested and merged after RPR-1021: OCIO, move from 1.1.1 to 2.1.1 [RPR-1021](https://amdrender.atlassian.net/browse/RPR-1021)

### CODE REVIEW

**Comment by ARozghon** [comment]
Tested with Blender 3.1, need to add warning about Emission in Uber Shader

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Review by bnagirniak — APPROVED** [review]
Tested - works ok with Blender 3.1

**Comment by bsavery** [comment]
Note.  This will require the OCIO change, but merging now.  Renders may be brighter.

**Review by bsavery — CHANGES_REQUESTED** [review]
@VascoPi Why don't you copy the OCIO config file from 3.0 to use in this case until we get the RPR fix?

**Comment by VascoPi** [comment]
I've updated the PR with OCIO config file fix but still appears brightness issue compare to Blender 3.0 and Blender 3.1. I keep going to find a solution.

**Review by ARozghon — APPROVED** [review]
now working with Blender 3.1 correctly. after the merge will need to update scenes for autotests

**Review by DagerD — APPROVED** [review]
Tested. Works.

**Pull request merged**
