### PR TITLE
RPRBLND-2122: Nodes are not removed after clicking "Convert Principled to Uber"

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Nodes are not removed after clicking "Convert Principled to Uber".

### EFFECT OF CHANGE
Principled DSDF node is removed after "Convert Principled to Uber".

### TECHNICAL STEPS
added remove function for Principled DSDF node.

### CODE REVIEW

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Comment by bsavery** [comment]
Question.  Why SHOULD the principled node be removed?  I think I wrote the original code and left it in on purpose.

**Review by bnagirniak — APPROVED** [review]
Looks good

**Comment by bsavery** [comment]
My original intention was to leave the Principled node in case the user wanted to switch back.

**Comment by VascoPi** [comment]
Not valid.

**Pull request closed without merging**
