### PR TITLE
RPRBLND-1743: RPR get an error with Tile render.

### PR DESCRIPTION
**Pull request by bnagirniak**
### PURPOSE
This is regression after Refactor Contour rendering functionality and UI RPRBLND-1708 (#271)

### EFFECT OF CHANGE
Fixed regression error with tile rendering after "Refactor Contour rendering functionality and UI"

### TECHNICAL STEPS
Reverted some changes after #271 with render_result creation.

### CODE REVIEW

**Review by ardraeiss — APPROVED** [review]
OK

**Review by ardraeiss — CHANGES_REQUESTED** [review]
Activating Contour rendering removes Combined result once Contour rendering is started.

**Comment by bnagirniak** [comment]
Latest issue is more complicated to fix, working on it. Moving PR to draft.

**Comment by bnagirniak** [comment]
Finished this task. 

### TECHNICAL STEPS
1. Implemented caching rendered images and use them for updating render results during contour rendering. This is done because during setting render result we have to fill all passes.
2. Separated contour render from other render by moving its code to _render_contour(). This is done for not mixing lot of functionality into _render() function for easier to maintain code.
3. Made code refactoring:
  - moved update_render_result() and _set_render_result() functions to RenderEngine as more related
  - move set_render_result into update_render_result.

**Review by ardraeiss — APPROVED** [review]
OK

**Pull request merged**
