### PR TITLE
RPRBLND-2222: Add all Toon Shader inputs

### PR DESCRIPTION
**Pull request by VascoPi**
### PURPOSE
Add all Toon Shader inputs.

### EFFECT OF CHANGE
**RPR Toon node UI.**
image

**Added features:**
_Mid Color as Albedo_ - shows the mid color on albedo AOV instead of base color.
_5 Colors_ - allows set additional 2 colors _Shadow Color 2, Highlight Color 2_.
_Light_ - light link setting: we can choose 1 light from the scene to lit its material.
_Transparency_ - make it transparent by blending toon and transparent material.

### TECHNICAL STEPS
Added support for input type MaterialNodeSetInputLightDataByKey. Adjusted light.sync, now it returns rpr_light. It returns already existing rpr_light or newly created. Added new features to RPRShaderNodeToon.
- bool properties: show_mix_levels, mid_color_as_albedo , five_colors, light
- inputs: "Shadow Color 2", "Highlight Color 2", "Transparency"
- light picker Adjusted viewport sync_update for object type bpy.types.Light. Now if a light is an update we update all materials which contain RPRShaderNodeToon and linked light as well.

### CODE REVIEW

**Review by ARozghon — APPROVED** [review]
working as expected. Approved by QA

**Review by bsavery — CHANGES_REQUESTED** [review]
From a UI perspective I would like to avoid the "pile of settings" that we get from northstar.  Here is my suggestion:

1. Always show the transparency slider
2.  Only two modes, with an advanced button.  Advanced always turns on the mid levels mixer and 5 colors etc. 
3.  Remove the mix levels and  5 colors thing, they should be always on when advanced mode is enabled.
4.  Mid color as albedo option is ok in advanced mode.  
5.  What does the "light" selection do?  Lock in to use one light?   This needs a better label IMO. 
6.  What does shadow color 2 and highlight color 2 do?

**Comment by VascoPi** [comment]
> 

1, 2, 3, 4 Done
image

5. Changed UI label to "Linked Light" and added a description.
According to the feature description from core team:
"Toon light link setting: we can choose 1 light from the scene to lit its material. (RPR_MATERIAL_INPUT_LIGHT on RPR_MATERIAL_NODE_TOON_CLOSURE) now we can't set emissive object to it but only light object"

6. The five colors are a representation of the color ramp (discussed with RPR Maya team)
image

**Review by bnagirniak — APPROVED** [review]
Tested - works ok

**Review by DagerD — APPROVED** [review]

**Comment by bsavery** [comment]
So the input to this "ramp" is the light level?

I'm a bit confused because I don't see the "shadow level" or "highlight level 2" inputs.

Here's my thoughts.  
1.  Shadow color 2 -> Rename to "Shadow Color"
2. Shadow Color -> "Mid Shadow Color"
3.  Highlight Color -> Rename to "Mid Highlight Color"
4.  Highlight Color 2 -> Rename to "Highlight Color"

Just in the UI.

Then reorder the inputs to correspond to the order:
1.  Shadow Color
2.  Mid shadow level
3.  Mid Shadow Color
4.  Mid Level
5.  Mid Color
etc

**Comment by VascoPi** [comment]
image

Shadow Color 2 -> Shadow Color
Shadow color -> Mid Shadow Color
Highlight Color 2 -> Highlight Color
Highlight Color -> Mid Highlight Color

Added new sockets:
Highlight Level -> MATERIAL_INPUT_POSITION_HIGHLIGHT
Highlight Level Mix -> MATERIAL_INPUT_RANGE_HIGHLIGHT
Mid Shadow Level -> MATERIAL_INPUT_POSITION_SHADOW
Mid Shadow Level Mix -> MATERIAL_INPUT_RANGE_SHADOW

**Pull request merged**
